### Recuperar todos los libros
GET http://localhost:1234/books

### Recuperar un libro por id
GET http://localhost:1234/books/9b0220fc-7a85-11ee-83f-309c23a2b865

### Recuperar todos los libros por un género
GET https://bunbury-goanna-rnff.1.sg-1.fl0.io/movies?genre=ACTION

### Crear un libro con POST
POST http://localhost:1234/books
Content-Type: application/json

{
  "title": "In the Woods",
  "year": 2007,
  "author": "Tana French",
  "price": 11.50,
  "image": "https://upload.wikimedia.org/wikipedia/en/3/3c/In_the_Woods_cover.jpg",
  "rate": 4.1,
  "genre": [
    "Mystery"
  ]
}

### Borrar un libro
DELETE http://localhost:1234/books/f96c45c8-7a8c-11ee-8d3f-309c23a2b865

### Actualizar un libro
PATCH http://localhost:1234/books/64d4da882f83563ab4f40632
Content-Type: application/json

{
  "year": 2022
}